theme: jekyll-theme-minimal
title: Munawira Kotyad
description: "Pursuing PhD in the CSE department at IIT Bombay. This is my professional page where I will be uploading projects and research progress. Email:Munawira[AT]gmail[DOT]com"
